image: Visual Studio 2017

install:
  - curl "http://msystem.waw.pl/x265/mingw-gcc91-20190503.7z" -L > mingw64.7z
  - 7z x mingw64.7z -oC:\msys64

before_deploy:
  - set MSYSTEM=MINGW64
  - rd /s /q C:\msys64\mingw64
  - C:\msys64\usr\bin\bash -lc 'pacman -Sy yasm --noconfirm; cd /c/projects/msys2-packages/ffmpeg-custom; PATH=/m64-91/bin:$PATH makepkg'
  - ps: Get-ChildItem C:\projects\msys2-packages\ffmpeg-custom\*pkg*.xz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  - set MSYSTEM=MSYS2
  - C:\msys64\usr\bin\bash -lc 'cd /c/projects/msys2-packages/aria2-custom; PATH=/m64-91/bin:$PATH makepkg;'
  - 7z a aria2c.7z C:\projects\msys2-packages\aria2-custom\src\aria2-master\src\aria2c.exe
  - appveyor PushArtifact aria2c.7z

deploy:
  artifact: /.*\.xz/
  auth_token:
    secure: J1DFsRUBaJKZ2HqHKOQEA427FUsKo6rDTxtxyUwARP7k0Ac5SgX1qn77+LYXdwk6
  description: ''
  on:
    appveyor_repo_tag: true
  provider: GitHub

branches:
  only:
    - latest

build: false