image: Visual Studio 2017

install:
  - curl "https://sourceforge.net/projects/mingw-w64-dgn/files/mingw-w64/mingw-w64-bin-x86_64-20180726.7z" -L > mingw64.7z
  - rd /s /q C:\msys64\mingw64
  - 7z x mingw64.7z -oC:\msys64

before_deploy:
  - set MSYSTEM=MINGW64
  - C:\msys64\usr\bin\bash -lc 'cd /c/projects/msys2-packages/ffmpeg-custom; sed -i 's/$(AR)/ar/' ffbuild/library.mak; makepkg'
  - ps: Get-ChildItem C:\projects\msys2-packages\ffmpeg-custom\*pkg*.xz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
  artifact: /.*\.xz/
  auth_token:
    secure: J1DFsRUBaJKZ2HqHKOQEA427FUsKo6rDTxtxyUwARP7k0Ac5SgX1qn77+LYXdwk6
  description: ''
  on:
    appveyor_repo_tag: true
  provider: GitHub

branches:
  only:
    - latest

build: false