image: Visual Studio 2017

environment:
  matrix:
    - toy: ffmpeg
    - toy: aria2

install:
  - curl "http://msystem.waw.pl/x265/mingw-gcc92-20191116.7z" -L > mingw64.7z
  - 7z x mingw64.7z -oC:\msys64
  - rd /s /q C:\msys64\mingw64
  - move C:\msys64\m64-92 C:\msys64\mingw64

before_deploy:
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
  - set MSYSTEM=MINGW64
  - C:\msys64\usr\bin\bash -lc 'pacman -Sy nasm --noconfirm'
  - C:\msys64\usr\bin\bash -lc 'pacman -Rdd binutils isl mpc msys2-runtime-devel msys2-w32api-headers msys2-w32api-runtime windows-default-manifest gcc gcc-fortran --noconfirm'
  - C:\msys64\usr\bin\bash -lc 'cd /c/projects/msys2-packages/%toy%-custom; makepkg'
  - ps: Get-ChildItem C:\projects\msys2-packages\ffmpeg-custom\*pkg*.xz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - if %toy%==aria2 7z a aria2c.7z C:\projects\msys2-packages\aria2-custom\src\aria2*\src\aria2c.exe && appveyor PushArtifact aria2c.7z

deploy:
  artifact: /.*\.*z/
  auth_token:
    secure: J1DFsRUBaJKZ2HqHKOQEA427FUsKo6rDTxtxyUwARP7k0Ac5SgX1qn77+LYXdwk6
  description: ''
  on:
    appveyor_repo_tag: true
  provider: GitHub

branches:
  only:
    - latest

build: false