image: Visual Studio 2017

install:
  - curl "http://msystem.waw.pl/x265/mingw-gcc91-20190503.7z" -L > mingw64.7z
  - rd /s /q C:\msys64\mingw64
  - 7z x mingw64.7z -oC:\msys64

before_deploy:
  - set MSYSTEM=MINGW64
  - C:\msys64\usr\bin\bash -lc 'export PATH=/m64-91/bin:$PATH; pacman -S yasm --noconfirm; cd /c/projects/msys2-packages/ffmpeg-custom; makepkg'
  - ps: Get-ChildItem C:\projects\msys2-packages\ffmpeg-custom\*pkg*.xz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
  artifact: /.*\.xz/
  auth_token:
    secure: J1DFsRUBaJKZ2HqHKOQEA427FUsKo6rDTxtxyUwARP7k0Ac5SgX1qn77+LYXdwk6
  description: ''
  on:
    appveyor_repo_tag: true
  provider: GitHub

branches:
  only:
    - latest

build: false