name: aria2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        install: >-
          make
          patch
    - name: Build
      shell: msys2 {0}
      run: |
        curl http://msystem.waw.pl/x265/mingw-gcc102-20200925.7z > mingw64.7z
        '/c/Program Files/7-Zip/7z' x mingw64.7z
        mv m64-102/* /mingw64
        cd /d/a/MSYS2-packages/MSYS2-packages/aria2
        makepkg
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: aria2/*.zst
        tag: latest
        overwrite: true
        file_glob: true
